# Welcome to Ficclat!

# Site settings
title: Ficclat - Ficción Latinoamericana
email: ficcionlatinoamericana@gmail.com
description: >
  Ficclat es un sitio web dedicado a la difusión de la ficción latinoamericana, especialmente en los géneros de terror, fantasía y ciencia ficción. Promovemos y damos a conocer las obras de autores latinoamericanos y brindamos un espacio para que los lectores puedan descubrir nuevas historias emocionantes y llenas de creatividad.
baseurl: "/ficclat" # the subpath of your site, e.g. /blog
url: "https://ficclat.github.io" # the base hostname & protocol for your site

twitter_username: ficcLat
github_username:  ficclat
facebook_username: ficclat
facebookgroup_username: ficclat
facebookgroup_number: '718730956035801'
instagram_username: ficclat_
youtube_username: ficclat

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Author settings (optional)
author:
  Equipo Ficclat.

# Social links
social:
  twitter: https://x.com/FiccLat
  youtube: https://www.youtube.com/@ficclat
  instagram: https://www.instagram.com/ficclat_/
  patreon: https://www.patreon.com/FiccLat
  facebook: https://web.facebook.com/groups/718730956035801

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include these items.
include:
  - _pages

# Permalinks settings
permalink: pretty

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Equipo Ficclat"

# Pagination settings (optional)
paginate: 5
paginate_path: "/page:num/"

# Minima theme settings
minima:
  social_links:
    twitter: FiccLat
    github: ficclat
    youtube: ficclat
    instagram: ficclat_
    patreon: FiccLat
collections:
  ezine:
    output: true
    permalink: /ezine/:path/